// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8fJP8OrvslixiIbxhrkufWT41Dkf4wtg',
    appId: '1:421776860617:web:e440f8df686dfacd3d7418',
    messagingSenderId: '421776860617',
    projectId: 'budget-app-537e9',
    authDomain: 'budget-app-537e9.firebaseapp.com',
    storageBucket: 'budget-app-537e9.firebasestorage.app',
    measurementId: 'G-BYG7PSJB8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvisbyEzxi46_O8oMGvCYNlcBgplbu0_Q',
    appId: '1:421776860617:android:d0988dea631d47cd3d7418',
    messagingSenderId: '421776860617',
    projectId: 'budget-app-537e9',
    storageBucket: 'budget-app-537e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJyqRjH5g3K7u7ZeRrc25o2UxrHRzIw4',
    appId: '1:421776860617:ios:361f80b671b76e163d7418',
    messagingSenderId: '421776860617',
    projectId: 'budget-app-537e9',
    storageBucket: 'budget-app-537e9.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJyqRjH5g3K7u7ZeRrc25o2UxrHRzIw4',
    appId: '1:421776860617:ios:361f80b671b76e163d7418',
    messagingSenderId: '421776860617',
    projectId: 'budget-app-537e9',
    storageBucket: 'budget-app-537e9.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8fJP8OrvslixiIbxhrkufWT41Dkf4wtg',
    appId: '1:421776860617:web:a5d5cc7ec7b332573d7418',
    messagingSenderId: '421776860617',
    projectId: 'budget-app-537e9',
    authDomain: 'budget-app-537e9.firebaseapp.com',
    storageBucket: 'budget-app-537e9.firebasestorage.app',
    measurementId: 'G-F4BQL9ZX9C',
  );
}
